name: contract-analyzer
services:
- name: web
  source_dir: /
  github:
    repo: your-username/contract-analyzer
    branch: main
  run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  health_check:
    http_path: /api/health
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: production

databases:
- name: contract-analyzer-db
  engine: PG
  version: "15"