services:
  - type: web
    name: contract-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: contract-analyzer-db
          property: connectionString
      - key: ENVIRONMENT
        value: production

databases:
  - name: contract-analyzer-db
    databaseName: contract_analyzer
    user: postgres